# Generated by Django 4.1.1 on 2022-10-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iot',
            name='id',
        ),
        migrations.AddField(
            model_name='iot',
            name='prime',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
