# Generated by Django 4.1.1 on 2022-09-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=7)),
                ('info', models.CharField(default='', max_length=50, verbose_name='信息')),
                ('date', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('int', models.IntegerField(default='0')),
                ('textfiel', models.TextField()),
            ],
        ),
    ]
