# Generated by Django 4.1.1 on 2022-09-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_test', '0002_book_int2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
