# Generated by Django 4.1.1 on 2022-09-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_test', '0003_alter_book_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='int3',
            field=models.IntegerField(default=0),
        ),
    ]
