# Generated by Django 4.1.1 on 2022-09-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_test', '0004_book_int3'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
