# Generated by Django 4.1.1 on 2022-09-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_test', '0005_card'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table='card',
        ),
    ]
